name: 'Invite User'
description: 'Invites a user into a GitHub organization.'
author: 'Froilán Irizarry Rivera'
inputs:
  CONFI_PATH:
    description: 'The path to the parsing rules'
    required: true
    default: '.github/parsing_rules.json'
  EMAIL:
    description: 'The email of the user to invite into the GitHub organization.'
    required: true
  USER_ROLE:
    description: 'The default role to apply to the user being invited to the organization.'
    required: true
outputs:
  message:
    description: 'Message output. Can be of actions taken or an error message.'
  stepStatus:
    description: 'The status of the current step. Values should be `success` or `failed`.'
runs:
  using: 'node12'
  main: 'dist/index.js'
