name: "build-test"
on: # rebuild any PRs and main branch changes
  pull_request:
  push:
    branches:
      - master
      - 'releases/*'

jobs:
  build: # make sure build/ci work properly
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - run: |
        rm .npmrc
        echo "@chocrates:registry=http://npm.pkg.github.com/:_authToken=${{ secrets.OCTOMOCK_READ_PACKAGE }}" > ~/.npmrc
        npm install
        npm run all
  test: # make sure the action works on a clean machine without building
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: ./
      with: 
        milliseconds: 1000
